name: Publish Site
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  checkout-source:
    runs-on: ubuntu-latest
    steps:
      - name: event name
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: runner info
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: repo info
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace  }}
      - name: job status
        run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./root # Set this to the directory where your site's build output is located
